### PR TITLE
Include digest of built image in image info file

### PR DESCRIPTION
**Pull request by mthalman**
In order to support #79, we need to be tracking the digest values of the images that get published.  These changes update the Build command to include the digest value in the image info file it outputs.  

Since the digest value isn't known until the image is pushed, the ordering of the logic had to be changed.  Previously, the image info file was written immediately after the images had been built.  Now we need to wait until after the images have been pushed so that we can retrieve the digest values and update the image info model appropriately.

### CODE REVIEW

**Comment by MichaelSimons** [comment]
Have you validated the digest remains the same as the images get ingested into MCR?  My understanding is a repo digest is repo specific.  Technically the staging repo is a different repo than the MCR repo.  Even if it the same today, is it something that will be guaranteed?  Official Docker repos collect the digest but they do it via pulling published images.  What they collect from the image is the ID.  I feel like this might be a better approach for us.  e.g. we should just collect the ID from our build process. 

Do these changes handle the multi-platform tags?

**Comment by mthalman** [comment]
> Have you validated the digest remains the same as the images get ingested into MCR? My understanding is a repo digest is repo specific. Technically the staging repo is a different repo than the MCR repo. Even if it the same today, is it something that will be guaranteed? Official Docker repos collect the digest but they do it via pulling published images. What they collect from the image is the ID. I feel like this might be a better approach for us. e.g. we should just collect the ID from our build process.
> 
> Do these changes handle the multi-platform tags?

Yes, the digest is the same between registries.  I can investigate how things would work to defer the retrieval until later in the pipeline.

**Comment by mthalman** [comment]
> Do these changes handle the multi-platform tags?

Yes, because the build is platform-specific.  It's probably actually simpler to handle it this way than deferring it to later in the pipeline because of that fact.

**Comment by MichaelSimons** [comment]
> Do these changes handle the multi-platform tags?
> 
> Yes, because the build is platform-specific. It's probably actually simpler to handle it this way than deferring it to later in the pipeline because of that fact.

I'm not seeing how this is done, what am I missing?  The multi-platform tags that I'm referring to are the ones produced by the PublishManifestCommand.

**Comment by MichaelSimons** [comment]
Closing until we settle on an overall plan for tag details.

**Pull request closed without merging**
