### PR TITLE
dotnet-docker bug 1346

### PR DESCRIPTION
**Pull request by robmccready**
Related to [bug 1346 pull request](https://github.com/dotnet/dotnet-docker/pull/1357)

Update common files to pass -PullImages instead of -IsLocalRun to run-tests.ps1

I think (not 100%) this is correct per discussion, but since it affects server side build stuff I'm not sure how to test locally to be sure.

### CODE REVIEW

**Comment by MichaelSimons** [comment]
@robmccready - It would be best to make all of the changes in the [dotnet-docker PR](https://github.com/dotnet/dotnet-docker/pull/1357) first.  Once we settle on a solution and verify it is all working we will backport the `/eng/common` changes to this repo.  I apologize for not making that clear before.

**Comment by robmccready** [comment]
That makes sense. I wasn't sure how the process of items moving from docker-tools to dotnet-docker worked so I pushed both at the same time. I've updated the PR on the dotnet-docker side with the template changes.

**Comment by MichaelSimons** [comment]
@robmccready - can you please update this PR to match https://github.com/dotnet/dotnet-docker/pull/1357?

**Comment by robmccready** [comment]
Ha. I was waiting for the tests to pass before commenting that I made the change. Looks like you already approved it. :)

**Comment by MichaelSimons** [comment]
Thanks @robmccready for migrating the infra changes here.

**Pull request merged**
