### PR TITLE
Specify ACR for Copying Images

### PR DESCRIPTION
**Pull request by ellahathaway**
Related to https://github.com/dotnet/dotnet-docker-internal/issues/5024 and https://github.com/dotnet/dotnet-docker-internal/issues/5026

This PR updates the `CopyAcrImages` command to include a `SourceRegistry` argument. This argument is necessary for copying the images from the staging directory to the publish directory. The corresponding tests have also been updated.

[Test pipeline run](https://dev.azure.com/dnceng/internal/_build/results?buildId=2459246&view=results)

### CODE REVIEW

**Comment by lbussell** [comment]
@ellahathaway you can rebase on https://github.com/dotnet/docker-tools/pull/1297 and begin testing. I'll be pushing some additional commits to fix the pipelines. If you want to get started now, you can just continue rebasing as I apply the updates.

**Review by mthalman — APPROVED** [review]

**Comment by ellahathaway** [comment]
IK that @MichaelSimons had some offline questions about the pipeline changes, so should I wait to merge this until we close out on that discussion?

**Comment by MichaelSimons** [comment]
> IK that @MichaelSimons had some offline questions about the pipeline changes, so should I wait to merge this until we close out on that discussion?

I don't think waiting is necessary on this PR.  They should be answered before https://github.com/dotnet/docker-tools/pull/1309 is merged.

**Comment by ellahathaway** [comment]
Had to adjust the PR in https://github.com/dotnet/docker-tools/pull/1295/commits/1e6dcfd342970af0bf577f54c4a0b38f837519ff to use the srcResourceId. This was necessary to fix a cred issue that arose after I made changes in https://github.com/dotnet/docker-tools/pull/1309 to use a different resource group and subscription for the new ACR.

**Comment by ellahathaway** [comment]
[New test run](https://dev.azure.com/dnceng/internal/_build/results?buildId=2462647&view=results) (internal Microsoft link)

**Review by mthalman — APPROVED** [review]

**Comment by mthalman** [comment]
Yeah, we should be good now.

**Pull request merged**
